
CREATE DATABASE secureprogramming;

--change to the db: 
--   \c secureprogramming

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS topics CASCADE;
DROP TABLE IF EXISTS messages CASCADE;



CREATE TABLE if not exists users(
username VARCHAR(60) PRIMARY KEY NOT NULL,
passwd VARCHAR(100) NOT NULL
);

CREATE TABLE if not exists topics (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
topic VARCHAR(100) NOT NULL,
op VARCHAR(60) NOT NULL
);

CREATE TABLE if not exists messages (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
topic int NOT NULL REFERENCES topics(id),
op VARCHAR(60) NOT NULL,
message VARCHAR(10000) NOT NULL
);


DROP ROLE IF EXISTS secureprog;
CREATE ROLE secureprog LOGIN PASSWORD 'secureprog';

GRANT SELECT, INSERT ON users TO secureprog;
GRANT SELECT, INSERT ON topics TO secureprog;
GRANT SELECT, INSERT ON messages TO secureprog;
--UPDATE, DELETE
